plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.142'
}

group = mod_group_id
version = mod_version

base {
    archivesName = "ftbpublicclaims-neoforge-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    maven { url = 'https://maven.ftb.dev/releases' }
    maven { url = 'https://maven.architectury.dev/' }
}

neoForge {
    version = project.neo_version

    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation "dev.architectury:architectury-neoforge:${architectury_version}"
    implementation "dev.ftb.mods:ftb-library-neoforge:${ftb_library_version}"
    implementation "dev.ftb.mods:ftb-teams-neoforge:${ftb_teams_version}"
    implementation "dev.ftb.mods:ftb-chunks-neoforge:${ftb_chunks_version}"

    def buyClaimChunksJar = file('libs/buyclaimchunks-continued-neoforge-1.21.1-1.1.1.jar')
    if (buyClaimChunksJar.exists()) {
        runtimeOnly files(buyClaimChunksJar)
    }

    testImplementation platform('org.junit:junit-bom:5.14.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            ftb_chunks_version     : ftb_chunks_version,
            ftb_teams_version      : ftb_teams_version,
            ftb_library_version    : ftb_library_version,
            architectury_version   : architectury_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
